// Generated by GoX

package door

import (
	"context"
	"fmt"
	
	"github.com/doors-dev/doors"
	"github.com/doors-dev/doors/internal/test"
	"github.com/doors-dev/gox"
)

type FragmentMany struct {
	n doors.Door
	test.NoBeam
}

func (f *FragmentMany) sample() gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		__e = __c.Init("div"); if __e != nil { return }
		{
			__e = __c.AttrSet("class", "sample"); if __e != nil { return }
			__e = __c.Submit(); if __e != nil { return }
			__e = __c.Text("sample"); if __e != nil { return }
		}
		__e = __c.Close(); if __e != nil { return }
	return })
}

func (f *FragmentMany) manyDoors() gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		for i := range 20 {
			__e = __c.Init("span"); if __e != nil { return }
			{
				__e = __c.AttrSet("style", "display:none"); if __e != nil { return }
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.Any(fmt.Sprint(i)); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
			__e = __c.Any(&f.n); if __e != nil { return }
		}
	return })
}

func (f *FragmentMany) replaced() gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		f.n.Replace(ctx, f.sample())

		for i := range 100 {
			__e = __c.Init("span"); if __e != nil { return }
			{
				__e = __c.AttrSet("style", "display:none"); if __e != nil { return }
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.Any(fmt.Sprint(i)); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
			__e = __c.Any(&f.n); if __e != nil { return }
		}
	return })
}

func (f *FragmentMany) Main() gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		f.n.Update(ctx, f.sample())
		n := doors.Door{}

		__e = n.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.InitContainer(); if __e != nil { return }
			{
				__e = __c.Any(f.manyDoors()); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
		__e = __c.Any(test.Button("replace", func(ctx context.Context) bool { 
		n.Update(ctx, f.replaced()) 
		return true
	})); if __e != nil { return }
	return })
}

type FragmentX struct {
	report doors.Door
	n doors.Door
	test.NoBeam
}

func (f *FragmentX) rep(ctx context.Context, s string) {
	f.report.Update(ctx, test.Report(s))
}

func (f *FragmentX) Main() gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		__e = f.n.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.InitContainer(); if __e != nil { return }
			{
				__e = __c.Any(test.Marker("init")); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
		__e = f.report.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = doors.AClick{
		On: func(ctx context.Context, _ doors.REvent[doors.PointerEvent]) bool {
			ch := f.n.XUpdate(ctx, test.Marker("updated"))
			err, ok := <-ch
			if !ok {
				f.rep(ctx, "channel closed")
				return true
			}
			if err != nil {
				f.rep(ctx, "channel err: " + err.Error())
				return true
			}
			f.rep(ctx, "ok")
			return false
		},
	}.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
				ctx := __c.Context(); __c.Noop(ctx)
				__e = __c.Init("button"); if __e != nil { return }
				{
					__e = __c.AttrSet("id", "updatex"); if __e != nil { return }
					__e = __c.Submit(); if __e != nil { return }
					__e = __c.Text("C"); if __e != nil { return }
				}
				__e = __c.Close(); if __e != nil { return }
			return })); if __e != nil { return }
		return })); if __e != nil { return }
		__e = __c.Init("script"); if __e != nil { return }
		{
			__e = __c.AttrSet("data:dd", "dd"); if __e != nil { return }
			__e = __c.Submit(); if __e != nil { return }
			__e = __c.Raw("alert(1)"); if __e != nil { return }
		}
		__e = __c.Close(); if __e != nil { return }
		__e = doors.AClick{
		On: func(ctx context.Context, _ doors.REvent[doors.PointerEvent]) bool {
			ch := f.n.XRemove(ctx)
			err, ok := <-ch
			if !ok {
				f.rep(ctx, "channel closed")
				return true
			}
			if err != nil {
				f.rep(ctx, "channel err: " + err.Error())
				return true
			}
			f.rep(ctx, "ok")
			return true
		},
	}.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.Init("button"); if __e != nil { return }
			{
				__e = __c.AttrSet("id", "removex"); if __e != nil { return }
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.Text("R"); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
	return })
}

type EmbeddedFragment struct {
	n1 doors.Door
	n2 doors.Door
	n3 doors.Door
	test.NoBeam
}

func (f *EmbeddedFragment) Main() gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		__e = f.n1.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.InitContainer(); if __e != nil { return }
			{
				__e = f.n2.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
					ctx := __c.Context(); __c.Noop(ctx)
					__e = __c.Init("div"); if __e != nil { return }
					{
						__e = __c.Submit(); if __e != nil { return }
						__e = __c.Any(test.Marker("init")); if __e != nil { return }
					}
					__e = __c.Close(); if __e != nil { return }
				return })); if __e != nil { return }
				__e = __c.Any(test.Marker("static")); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
		__e = __c.Any(&f.n3); if __e != nil { return }
		__e = __c.Init("button"); if __e != nil { return }
		{
			__e = __c.AttrSet("id", "remove"); if __e != nil { return }
			__e = __c.AttrMod(doors.AClick{
			On: func(ctx context.Context, _ doors.REvent[doors.PointerEvent]) bool {
				f.n2.Remove(ctx)
				return true
			},
		}); if __e != nil { return }
			__e = __c.Submit(); if __e != nil { return }
			__e = __c.Text("C"); if __e != nil { return }
		}
		__e = __c.Close(); if __e != nil { return }
		__e = __c.Init("button"); if __e != nil { return }
		{
			__e = __c.AttrSet("id", "clear"); if __e != nil { return }
			__e = __c.AttrMod(doors.AClick{
			On: func(ctx context.Context, _ doors.REvent[doors.PointerEvent]) bool {
				f.n1.Clear(ctx)
				return true
			},
		}); if __e != nil { return }
			__e = __c.Submit(); if __e != nil { return }
			__e = __c.Text("C"); if __e != nil { return }
		}
		__e = __c.Close(); if __e != nil { return }
		__e = __c.Init("button"); if __e != nil { return }
		{
			__e = __c.AttrSet("id", "replace"); if __e != nil { return }
			__e = __c.AttrMod(doors.AClick{
			On: func(ctx context.Context, _ doors.REvent[doors.PointerEvent]) bool {
				f.n2.Update(ctx, test.Marker("replaced"))
				f.n3.Update(ctx, test.Marker("temp"))
				f.n3.Replace(ctx, &f.n2)
				return true
			},
		}); if __e != nil { return }
			__e = __c.Submit(); if __e != nil { return }
			__e = __c.Text("C"); if __e != nil { return }
		}
		__e = __c.Close(); if __e != nil { return }
	return })
}

type DynamicFragment struct {
	n1 doors.Door
	n2 doors.Door
	test.NoBeam
}

func (f *DynamicFragment) Main() gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		f.n1.Update(ctx, test.Marker("init"))

		__e = f.n1.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.Init("div"); if __e != nil { return }
			{
				__e = __c.Submit(); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
		__e = __c.Init("button"); if __e != nil { return }
		{
			__e = __c.AttrSet("id", "update"); if __e != nil { return }
			__e = __c.AttrMod(doors.AClick{
			On: func(ctx context.Context, _ doors.REvent[doors.PointerEvent]) bool {
				f.n1.Update(ctx, test.Marker("updated"))
				return true
			},
		}); if __e != nil { return }
			__e = __c.Submit(); if __e != nil { return }
			__e = __c.Text("U"); if __e != nil { return }
		}
		__e = __c.Close(); if __e != nil { return }
		__e = __c.Init("button"); if __e != nil { return }
		{
			__e = __c.AttrSet("id", "replace"); if __e != nil { return }
			__e = __c.AttrMod(doors.AClick{
			On: func(ctx context.Context, _ doors.REvent[doors.PointerEvent]) bool {
				f.n2.Update(ctx, test.Marker("replaced"))
				f.n1.Replace(ctx, &f.n2)
				return true
			},
		}); if __e != nil { return }
			__e = __c.Submit(); if __e != nil { return }
			__e = __c.Text("Rp"); if __e != nil { return }
		}
		__e = __c.Close(); if __e != nil { return }
		__e = __c.Init("button"); if __e != nil { return }
		{
			__e = __c.AttrSet("id", "remove"); if __e != nil { return }
			__e = __c.AttrMod(doors.AClick{
			On: func(ctx context.Context, _ doors.REvent[doors.PointerEvent]) bool {
				f.n2.Remove(ctx)
				return true
			},
		}); if __e != nil { return }
			__e = __c.Submit(); if __e != nil { return }
			__e = __c.Text("Remove"); if __e != nil { return }
		}
		__e = __c.Close(); if __e != nil { return }
	return })
}

type BeforeFragment struct {
	doorInit doors.Door
	doorUpdate doors.Door
	doorRemoved doors.Door
	doorReplaced doors.Door
	test.NoBeam
}

func (f *BeforeFragment) Main() gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		__e = f.doorInit.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.Init("div"); if __e != nil { return }
			{
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.Any(test.Marker("init")); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
		f.doorUpdate.Update(ctx, test.Marker("updated"))

		__e = f.doorUpdate.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.Init("div"); if __e != nil { return }
			{
				__e = __c.Submit(); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
		f.doorRemoved.Update(ctx, test.Marker("removed"))

		f.doorRemoved.Remove(ctx)

		__e = __c.Any(&f.doorRemoved); if __e != nil { return }
		f.doorReplaced.Replace(ctx, test.Marker("replaced"))

		__e = f.doorReplaced.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.Init("div"); if __e != nil { return }
			{
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.Any(test.Marker("initReplaced")); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
	return })
}