// Generated by GoX

package attr

import (
	"context"
	
	"github.com/doors-dev/doors"
	"github.com/doors-dev/doors/internal/test"
	"github.com/doors-dev/gox"
)

type dynaFragment struct {
	test.NoBeam
	n doors.Door
	v1 string
	v2 string
}

func (f *dynaFragment) content(da1 doors.ADyn, da2 doors.ADyn) gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		__e = da1.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = da2.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
				ctx := __c.Context(); __c.Noop(ctx)
				__e = __c.Init("div"); if __e != nil { return }
				{
					__e = __c.AttrSet("id", "t1"); if __e != nil { return }
					__e = __c.Submit(); if __e != nil { return }
				}
				__e = __c.Close(); if __e != nil { return }
			return })); if __e != nil { return }
		return })); if __e != nil { return }
		__e = da1.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = da2.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
				ctx := __c.Context(); __c.Noop(ctx)
				__e = __c.Init("div"); if __e != nil { return }
				{
					__e = __c.AttrSet("id", "t2"); if __e != nil { return }
					__e = __c.Submit(); if __e != nil { return }
					__e = da1.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
						ctx := __c.Context(); __c.Noop(ctx)
						__e = da2.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
							ctx := __c.Context(); __c.Noop(ctx)
							__e = __c.Init("div"); if __e != nil { return }
							{
								__e = __c.AttrSet("id", "t3"); if __e != nil { return }
								__e = __c.Submit(); if __e != nil { return }
							}
							__e = __c.Close(); if __e != nil { return }
						return })); if __e != nil { return }
					return })); if __e != nil { return }
				}
				__e = __c.Close(); if __e != nil { return }
			return })); if __e != nil { return }
		return })); if __e != nil { return }
	return })
}

func (f *dynaFragment) buttons(index string, da doors.ADyn, value string) gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		__e = doors.AClick{
		On: func(ctx context.Context, r doors.REvent[doors.PointerEvent]) bool {
			da.Enable(ctx, true)
			return false
		},
	}.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.Init("button"); if __e != nil { return }
			{
				__e = __c.AttrSetAny("id", "enable-" + index); if __e != nil { return }
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.Text("enable-"); if __e != nil { return }
				__e = __c.Any(index); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
		__e = doors.AClick{
		On: func(ctx context.Context, r doors.REvent[doors.PointerEvent]) bool {
			da.Enable(ctx, false)
			return false
		},
	}.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.Init("button"); if __e != nil { return }
			{
				__e = __c.AttrSetAny("id", "disable-" + index); if __e != nil { return }
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.Text("disable-"); if __e != nil { return }
				__e = __c.Any(index); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
		__e = doors.AClick{
		On: func(ctx context.Context, r doors.REvent[doors.PointerEvent]) bool {
			da.Value(ctx, value)
			return false
		},
	}.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.Init("button"); if __e != nil { return }
			{
				__e = __c.AttrSetAny("id", "update-" + index); if __e != nil { return }
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.Text("update-"); if __e != nil { return }
				__e = __c.Any(index); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
	return })
}

func (f *dynaFragment) Main() gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		da1 := doors.NewADyn("data-test1", f.v1, true)

		da2 := doors.NewADyn("data-test2", f.v2, false)

		__e = f.n.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.InitContainer(); if __e != nil { return }
			{
				__e = __c.Any(f.content(da1, da2)); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
		__e = __c.Any(f.buttons("1", da1, f.v2)); if __e != nil { return }
		__e = __c.Any(f.buttons("2", da2, f.v1)); if __e != nil { return }
		__e = doors.AClick{
		On: func(ctx context.Context, r doors.REvent[doors.PointerEvent]) bool {
			da1.Value(ctx, f.v1)
			da2.Value(ctx, f.v2)
			return false
		},
	}.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.Init("button"); if __e != nil { return }
			{
				__e = __c.AttrSet("id", "reset"); if __e != nil { return }
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.Text("reset"); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
		__e = doors.AClick{
		On: func(ctx context.Context, r doors.REvent[doors.PointerEvent]) bool {
			f.n.Clear(ctx)
			return false
		},
	}.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.Init("button"); if __e != nil { return }
			{
				__e = __c.AttrSet("id", "clear"); if __e != nil { return }
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.Text("clear"); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
		__e = doors.AClick{
		On: func(ctx context.Context, r doors.REvent[doors.PointerEvent]) bool {
			f.n.Update(ctx, f.content(da1, da2))
			return false
		},
	}.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.Init("button"); if __e != nil { return }
			{
				__e = __c.AttrSet("id", "show"); if __e != nil { return }
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.Text("show"); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
		__e = doors.AClick{
		On: func(ctx context.Context, r doors.REvent[doors.PointerEvent]) bool {
			f.n.Replace(ctx, f.content(da1, da2))
			return true
		},
	}.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.Init("button"); if __e != nil { return }
			{
				__e = __c.AttrSet("id", "replace"); if __e != nil { return }
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.Text("replace"); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
	return })
}