// Generated by GoX

package attr

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	
	"github.com/doors-dev/doors"
	"github.com/doors-dev/doors/internal/test"
	"github.com/doors-dev/gox"
)

type formFragment struct {
	test.NoBeam
	r *test.Reporter
	raw bool
}

func (f *formFragment) Main() gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		f.r.Update(ctx, 0, "init")

		__e = __c.Any(f.r); if __e != nil { return }
		if f.raw {
			__e = __c.Any(f.form(f.submitRaw())); if __e != nil { return }
		} else  {
			__e = __c.Any(f.form(f.submitSimple())); if __e != nil { return }
		}
	return })
}

func (f *formFragment) submitSimple() doors.Attr {
	return doors.ASubmit[formData]{
		On: func(ctx context.Context, r doors.RForm[formData]) bool {
			f.r.Update(ctx, 0, r.Data().Name)
			f.r.Update(ctx, 1, r.Data().Email)
			f.r.Update(ctx, 2, fmt.Sprint(r.Data().Age))
			f.r.Update(ctx, 3, r.Data().Subscribe)
			return true
		},
	}
}
func (f *formFragment) submitRaw() doors.Attr {
	return doors.ARawSubmit{
		On: func(ctx context.Context, rf doors.RRawForm) bool {
			form, _ := rf.ParseForm(10_000_000)
			fileHeader := form.Form().File["attachment"][0]
			file, err := fileHeader.Open()
			if err != nil {
				return true
			}
			defer file.Close()
			hasher := sha256.New()
			if _, err := io.Copy(hasher, file); err != nil {
				return true
			}
			hash := hex.EncodeToString(hasher.Sum(nil))
			f.r.Update(ctx, 0, hash)
			return true
		},
	}
}

type formData struct {
	Name string `form:"name"`
	Email string `form:"email"`
	Age int `form:"age"`
	Subscribe string `form:"subscribe"`
}

func (f *formFragment) form(a doors.Attr) gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		__e = a.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.Init("form"); if __e != nil { return }
			{
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.InitVoid("input"); if __e != nil { return }
				{
					__e = __c.AttrSet("type", "text"); if __e != nil { return }
					__e = __c.AttrSet("id", "name"); if __e != nil { return }
					__e = __c.AttrSet("name", "name"); if __e != nil { return }
				}
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.InitVoid("input"); if __e != nil { return }
				{
					__e = __c.AttrSet("type", "email"); if __e != nil { return }
					__e = __c.AttrSet("id", "email"); if __e != nil { return }
					__e = __c.AttrSet("name", "email"); if __e != nil { return }
				}
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.InitVoid("input"); if __e != nil { return }
				{
					__e = __c.AttrSet("type", "number"); if __e != nil { return }
					__e = __c.AttrSet("id", "age"); if __e != nil { return }
					__e = __c.AttrSet("name", "age"); if __e != nil { return }
					__e = __c.AttrSet("min", "0"); if __e != nil { return }
				}
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.InitVoid("input"); if __e != nil { return }
				{
					__e = __c.AttrSet("type", "checkbox"); if __e != nil { return }
					__e = __c.AttrSet("id", "subscribe"); if __e != nil { return }
					__e = __c.AttrSet("name", "subscribe"); if __e != nil { return }
					__e = __c.AttrSet("value", "on"); if __e != nil { return }
				}
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.InitVoid("input"); if __e != nil { return }
				{
					__e = __c.AttrSet("type", "file"); if __e != nil { return }
					__e = __c.AttrSet("id", "file"); if __e != nil { return }
					__e = __c.AttrSet("name", "attachment"); if __e != nil { return }
				}
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.Init("button"); if __e != nil { return }
				{
					__e = __c.AttrSet("id", "submit"); if __e != nil { return }
					__e = __c.AttrSet("type", "submit"); if __e != nil { return }
					__e = __c.Submit(); if __e != nil { return }
					__e = __c.Text("Submit"); if __e != nil { return }
				}
				__e = __c.Close(); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
	return })
}