// Generated by GoX

package attr

import (
	"context"
	"fmt"
	
	"github.com/doors-dev/doors"
	"github.com/doors-dev/doors/internal/test"
	"github.com/doors-dev/gox"
)

type keyFragment struct {
	r *test.Reporter
	test.NoBeam
}

func (f *keyFragment) Main() gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		__e = doors.AKeyDown{
		On: func(ctx context.Context, r doors.REvent[doors.KeyboardEvent]) bool {
			f.r.Update(ctx, 0, r.Event().Key)
			f.r.Update(ctx, 1, "down")
			return false
		},
	}.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = doors.AKeyUp{
		On: func(ctx context.Context, r doors.REvent[doors.KeyboardEvent]) bool {
			f.r.Update(ctx, 2, r.Event().Key)
			f.r.Update(ctx, 3, "up")
			if r.Event().ShiftKey {
				f.r.Update(ctx, 4, fmt.Sprint(r.Event().ShiftKey))
			}
			if r.Event().CtrlKey {
				f.r.Update(ctx, 5, fmt.Sprint(r.Event().CtrlKey))
			}
			if r.Event().AltKey {
				f.r.Update(ctx, 6, fmt.Sprint(r.Event().AltKey))
			}
			return false
		},
	}.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
				ctx := __c.Context(); __c.Noop(ctx)
				__e = __c.InitVoid("input"); if __e != nil { return }
				{
					__e = __c.AttrSet("type", "text"); if __e != nil { return }
					__e = __c.AttrSet("id", "input"); if __e != nil { return }
					__e = __c.AttrSet("placeholder", ""); if __e != nil { return }
				}
				__e = __c.Submit(); if __e != nil { return }
			return })); if __e != nil { return }
		return })); if __e != nil { return }
		__e = __c.InitVoid("hr"); if __e != nil { return }
		{
		}
		__e = __c.Submit(); if __e != nil { return }
		f.r.Update(ctx, 0, "")
		f.r.Update(ctx, 1, "")
		f.r.Update(ctx, 2, "")
		f.r.Update(ctx, 3, "")
		f.r.Update(ctx, 4, "")
		f.r.Update(ctx, 5, "")
		f.r.Update(ctx, 6, "")

		__e = __c.Any(f.r); if __e != nil { return }
	return })
}