// Generated by GoX

package test

import (
	"context"
	"fmt"
	"net/http"
	
	"github.com/doors-dev/doors"
	"github.com/doors-dev/gox"
)

func Report(value string) gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		__e = __c.Any(ReportId(0, value)); if __e != nil { return }
	return })
}

func ReportId(id int, value string) gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		__e = __c.Init("div"); if __e != nil { return }
		{
			__e = __c.AttrSetAny("id", fmt.Sprintf("report-%d", id)); if __e != nil { return }
			__e = __c.Submit(); if __e != nil { return }
			__e = __c.Any(value); if __e != nil { return }
		}
		__e = __c.Close(); if __e != nil { return }
	return })
}

func Marker(id string) gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		__e = __c.Init("div"); if __e != nil { return }
		{
			__e = __c.AttrSetAny("id", id); if __e != nil { return }
			__e = __c.Submit(); if __e != nil { return }
		}
		__e = __c.Close(); if __e != nil { return }
	return })
}

type page[P any]interface {
	h1() string
	content(doors.Source[P]) gox.Elem
	head(doors.Source[P]) gox.Elem
}

func Document[P any](p page[P], b doors.Source[P]) gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		__e = __c.Raw("<!DOCTYPE html>"); if __e != nil { return }
		__e = __c.Init("html"); if __e != nil { return }
		{
			__e = __c.AttrSet("lang", "en"); if __e != nil { return }
			__e = __c.Submit(); if __e != nil { return }
			__e = __c.Init("head"); if __e != nil { return }
			{
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.InitVoid("meta"); if __e != nil { return }
				{
					__e = __c.AttrSet("charset", "UTF-8"); if __e != nil { return }
				}
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.InitVoid("meta"); if __e != nil { return }
				{
					__e = __c.AttrSet("name", "viewport"); if __e != nil { return }
					__e = __c.AttrSet("content", "width=device-width, initial-scale=1.0"); if __e != nil { return }
				}
				__e = __c.Submit(); if __e != nil { return }
				__e = doors.ARawFileHref{
				Handler: func(w http.ResponseWriter, r *http.Request) {},
			}.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
					ctx := __c.Context(); __c.Noop(ctx)
					__e = __c.InitVoid("link"); if __e != nil { return }
					{
						__e = __c.AttrSet("rel", "icon"); if __e != nil { return }
						__e = __c.AttrSet("type", "image/png"); if __e != nil { return }
					}
					__e = __c.Submit(); if __e != nil { return }
				return })); if __e != nil { return }
				__e = __c.Any(p.head(b)); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
			__e = __c.Init("body"); if __e != nil { return }
			{
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.Init("h1"); if __e != nil { return }
				{
					__e = __c.Submit(); if __e != nil { return }
					__e = __c.Any(p.h1()); if __e != nil { return }
				}
				__e = __c.Close(); if __e != nil { return }
				__e = __c.Any(p.content(b)); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		}
		__e = __c.Close(); if __e != nil { return }
	return })
}

func NewReporter(size int) *Reporter {
	reports := make([]*doors.Door, size)
	for i := range size {
		reports[i] = &doors.Door{}
	}
	return &Reporter{
		reports: reports,
	}
}

type Reporter struct {
	reports []*doors.Door
}

func (r *Reporter) Update(ctx context.Context, i int, content string) {
	r.reports[i].Update(ctx, ReportId(i, content))
}

func (r *Reporter) Main() gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		for _, report := range r.reports {
			__e = __c.Any(report); if __e != nil { return }
		}
	return })
}

func Button(id string, handler func(context.Context) bool) gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		__e = doors.AClick{
		On: func(ctx context.Context, _ doors.REvent[doors.PointerEvent]) bool {
			return handler(ctx)
		},
	}.Proxy(__c, gox.Elem(func(__c gox.Cursor) (__e error) {
			ctx := __c.Context(); __c.Noop(ctx)
			__e = __c.Init("button"); if __e != nil { return }
			{
				__e = __c.AttrSetAny("id", id); if __e != nil { return }
				__e = __c.Submit(); if __e != nil { return }
				__e = __c.Any(id); if __e != nil { return }
			}
			__e = __c.Close(); if __e != nil { return }
		return })); if __e != nil { return }
	return })
}