// Generated by GoX

package test

import (
	"github.com/doors-dev/doors"
	"github.com/doors-dev/gox"
)

type NoBeam struct{}

func (f NoBeam) setBeam(_ doors.Source[Path]) {}

type Path struct {
	Vh bool `path:""`
	Vs bool `path:"/s"`
	Vp bool `path:"/s/:P"`
	P string
}

type Fragment interface {
	setBeam(b doors.Source[Path])
	gox.Comp
}

type Page struct {
	F Fragment
	H func(doors.Source[Path]) gox.Elem 
	Header string
}

func (p *Page) h1() string {
	return p.Header
}

func (p *Page) head(b doors.Source[Path]) gox.Elem{
	if p.H == nil {
		return nil
	}
	return p.H(b)
}

func (p *Page) content(b doors.Source[Path]) gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		if p.F != nil {
			p.F.setBeam(b)

			__e = __c.Any(p.F); if __e != nil { return }
		}
	return })
}

func (p *Page) Main(b doors.Source[Path]) gox.Elem {
	return gox.Elem(func(__c gox.Cursor) (__e error) {
		ctx := __c.Context(); __c.Noop(ctx)
		__e = __c.Any(Document(p, b)); if __e != nil { return }
	return })
}